//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCopyright("Copyright (c) Andreas Grimme 2016")]
[assembly: System.Reflection.AssemblyCompany("Andreas Grimme")]
[assembly: System.Reflection.AssemblyProduct("tta")]


